services:
  php:
    build: .
    container_name: uek-295
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.4
    container_name: php-backend
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
volumes:
  mysql_data: