<?php
namespace App\controller;

use App\service\AuthService;
use OpenApi\Attributes as OAT;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;


class AuthController {

    private AuthService $authenticationService;

    /**
     *  The constructor initializes the AuthService
     *
     * @param AuthService $authenticationService initializes the authentication-service
     */
    public function __construct(AuthService $authenticationService) {
        $this->authenticationService = $authenticationService;
    }


    /**
     *  Validates the input and returns a new signed jwt token generated by auth service -> jwt service
     *
     * @param ServerRequestInterface $request The incomming HTTP request.
     * @param ResponseInterface $response The Response Object
     * @param array $args The route argumments provided
     * @return ResponseInterface The json result containing the result.
    */

    #[OAT\Post(
        path: '/api/v1/authenticate',
        summary: 'Erstellt ein zugangs Token',
        tags: ['Authentifizierung'],
        requestBody: new OAT\RequestBody(
            required: true,
            description: 'Login Daten',
            content: new OAT\JsonContent(
                required: ['username', 'password'],
                properties: [
                    new OAT\Property(
                        property: 'username',
                        type: 'string',
                        example: 'admin'
                    ),
                    new OAT\Property(
                        property: 'password',
                        type: 'string',
                        example: 'sec!ReT423*&'
                    )
                ],
                type: 'object'
            )
        ),
        responses: [
            new OAT\Response(
                response: 200,
                description: 'Cookie wurde erstellt',
            ),
            new OAT\Response(
                response: 401,
                description: 'Ungültige Eingabe',
                content: new OAT\JsonContent(
                    properties: [
                        new OAT\Property(
                            property: 'error',
                            type: 'string',
                            example: 'Wrong username or password'
                        )
                    ]
                )
            ),
            new OAT\Response(
                response: 500,
                description: 'Unbekannter Serverfehler',
                content: new OAT\JsonContent(
                    properties: [
                        new OAT\Property(
                            property: 'fatal_error',
                            type: 'string',
                            example: "an unexpected error occurred"
                        )
                    ]
                )
            )
        ]
    )]
    public function authenticate(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface {

        $body = $request->getParsedBody();
        // Sets the username and password to null or to the given values
        $username = $body['username'] ?? null;
        $password = $body['password'] ?? null;

        // Creates a LoginRequest and saves the result in the loginresponse variable
        $loginresponse = $this->authenticationService->loginRequest($username, $password);

        // Checks if the response contains an error
        if (isset($loginresponse["error"])) {
            $response->getBody()->write(json_encode($loginresponse));
            $response = $response->withStatus(401)->withHeader('Content-Type', 'application/json');
            return $response;
        }
        // Checks if the response contains a fatal error
        if (isset($loginresponse["fatal_error"])) {
            $response->getBody()->write(json_encode($loginresponse));
            $response = $response->withStatus(500)->withHeader('Content-Type', 'application/json');
            return $response;
        }
        // Sets the token as a cookie
        setcookie("token", $loginresponse["token"]);
        $response = $response->withStatus(200)->withHeader('Content-Type', 'application/json');
        return $response;
    }


    /**
     *  Removes a JWT token from cookies
     *
     * @param ServerRequestInterface $request The incomming HTTP request.
     * @param ResponseInterface $response The Response Object
     * @param array $args The route argumments provided
     * @return ResponseInterface The json result containing the result.
     */


    #[OAT\Delete(
        path: '/api/v1/unauthenticate',
        summary: 'Meldet den Benutzer ab und entfernt den Token-Cookie',
        tags: ['Authentifizierung'],
        responses: [
            new OAT\Response(
                response: 204,
                description: 'Token wurde gelöscht',
            ),
            new OAT\Response(
                response: 401,
                description: 'Nicht authentifiziert',
                content: new OAT\JsonContent(
                    properties: [
                        new OAT\Property(
                            property: 'error',
                            type: 'string',
                            example: 'Missing token'
                        )
                    ],
                    type: 'object'
                )
            )
        ]
    )]
    public function unAuthenticate(ServerRequestInterface $request, $response, array $args): ResponseInterface {
        // Removes the token cookie
        setcookie("token", "", time() - 1);
        $response = $response->withStatus(204);
        return $response;
    }
}
